# Generated by Django 2.2.7 on 2020-07-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
