# Generated by Django 2.2.7 on 2020-07-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_item',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
