# Generated by Django 2.2.7 on 2020-08-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_item', '0003_auto_20200803_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_item',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
