# Generated by Django 2.2.7 on 2020-05-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200429_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
