# Generated by Django 2.2.7 on 2020-05-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200502_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
