# Generated by Django 2.2.7 on 2020-06-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200502_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='label',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='owner',
            field=models.CharField(max_length=50),
        ),
    ]
