# Generated by Django 2.2.7 on 2020-05-22 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='inv_number',
            new_name='bill_number',
        ),
    ]
