# Generated by Django 2.2.7 on 2020-04-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='balance',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='file',
            name='currency',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
