# Generated by Django 2.2.7 on 2020-05-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20200513_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='inv_number',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
    ]
