# Generated by Django 2.2.7 on 2020-06-22 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bill', '0002_auto_20200522_1219'),
        ('invoice', '0006_auto_20200522_1218'),
        ('account', '0005_auto_20200622_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
                ('ref_bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.Bill')),
                ('ref_inv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
